version: '3.8'

services:
  zai_quotecheck:
    build: .
    image: victorhdchagas/zai_quotecheck:latest
    container_name: zai_quotecheck
    volumes:
      - ${HOME}/.config/zai_quotecheck:/root/.config/zai_quotecheck
    environment:
      - TZ=America/Sao_Paulo
